application: israel-like
version: 1
runtime: python
api_version: 1

admin_console:
 pages:
 - name: Appstats
   url: /stats
      
handlers:
- url: /default_error.html
  static_files: static/heart.ico
  upload: static/heart.ico
- url: /favicon.ico
  static_files: static/heart.ico
  upload: static/heart.ico
- url: /fb_tab_template.html
  static_files: static/fbpromo.html
  upload: static/fbpromo.html
- url: /fetch
  script: pipeline.py
- url: /prepare_fetch
  script: pipeline.py
- url: /recalculate
  script: article_updater.py
- url: /cleandb
  script: article_updater.py
- url: /static
  static_dir: static
- url: /admin
  script: main.py
- url: /fb.*
  script: fbutils.py
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
- url: /.*
  script: main.py
